sudo: required
services:
- docker
language: bash
env:
- SERVICE=base
- SERVICE=python
- SERVICE=web
- SERVICE=worker
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -f docker/arm/Dockerfile-$SERVICE -t johncclayton/electric-pi-$SERVICE .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_JC_USER" -p="$DOCKER_JC_PASS"
    TAG=$TRAVIS_BUILD_NUMBER

    if [ "$SERVICE" == "base" ] || [ "$SERVICE" == "python" ]; then
      docker push johncclayton/electric-pi-$SERVICE
    else
      docker tag johncclayton/electric-pi-$SERVICE johncclayton/electric-pi-$SERVICE:$TAG
      docker push johncclayton/electric-pi-$SERVICE
    fi
  fi

jobs:
  include: 
    - stage: build SD image
      env:
        - YAY=amazeballs
      script: ./travis_webhook_to_build_sd_image.sh