version: '2'

services:
  web:
    image: johncclayton/electric-pi-web:${DOCKER_TAG}

    container_name: electric-web
    command: sh -x /www/run_gunicorn.sh

    environment:
      - ELECTRIC_WORKER_CONNECT=tcp://worker:5001

    ports:
      - "80:5000"
      - "5000:5000"

    restart: always

    depends_on:
      - worker

  worker:
    image: johncclayton/electric-pi-worker:${DOCKER_TAG}

    container_name: electric-worker
    command: sh -x /www/run_zmq_worker.sh
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb

    restart: always

