version: '2'

services:
  web:
    build:
      context: .
      dockerfile: docker/arm/Dockerfile
    image: scornflake/electric-pi

    container_name: electric-web

    ports:
      - "80:5000"
      - "5000:5000"

    volumes:
      - ./src/server:/www

    restart: always

    networks:
      - charger

networks:
  charger:
