version: '2'

services:
  worker:
    image: electric/web

    container_name: electric-worker

    ports:
      - "80:5000"
      - "5000:5000"

    privileged: true

    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./src/server:/www

  web:
    build:
      context: .
      dockerfile: docker/arm/Dockerfile
      image: electric/web

    container_name: electric-web

    ports:
      - "80:5000"
      - "5000:5000"

    volumes:
      - ./src/server:/www

    restart: always

    networks:
      - charger

  redis:
    image: hypriot/rpi-redis
    container_name: electric-redis

    ports:
      - "6379:6379"

    restart: always

    networks:
      - charger

networks:
  charger:
